### ISSUE TITLE
Status "info" is not working with type 3 or type 2

### ISSUE THREAD

**Issue by RickardAhlstedt** [simple-notify/simple-notify#35]
Hi!

The status "info" is not working when selecting type 3 or 2, as well as the icon returns as "undefined".
Is this intended or a oversight when you created the library?

Other than that, awesome library! I'm using it in a few Laravel-projects I'm working on :)

**Comment by Scriptfarmes** [comment]
The "Info" Palette ist is not implemented. 
 It's easy to extend the "simple-notify.min.js" and "simple-notify.min.css" files with a little code.

**Comment by dgknca** [comment]
hi folks. I haven't worked on this project for a long time and the last time I was working on version 1.0.0 but I never got it published. You can see that the latest avaiable version is `0.5.5`. It's nice to see that there are people using this package and I will be releasing version 1.0.0 later this week.

**Comment by dgknca** [comment]
v1.0.0 is just released.
