### ISSUE TITLE
CDN can’t be reached

### ISSUE THREAD

**Issue by harmaesa** [simple-notify/simple-notify#42]
Both https://cdn.jsdelivr.net/npm/simple-notify@0.5.5/dist/simple-notify.min.css and https://cdn.jsdelivr.net/npm/simple-notify@0.5.5/dist/simple-notify.min.js can’t be reached.

Please kindly advice asap as it will be used in production. Thanks.

**Comment by dgknca** [comment]
it looks accessible now. you can use unpkg cdn too if you want. 

`https://unpkg.com/simple-notify@0.5.5/dist/simple-notify.min.css`
`https://unpkg.com/simple-notify@0.5.5/dist/simple-notify.min.js`

**Comment by harmaesa** [comment]
Thanks mate. Its still not working though from my local nor production server.

![image](https://user-images.githubusercontent.com/33015388/209516490-8ca5eb58-7241-4e6c-9353-6ccc8098cf3f.png)

But anyway the unpkg is working so I will switch to it.

**Comment by jimaek** [comment]
If you have issues with jsDelivr please email dak@prospectone.io with more details. The service itself is online without any problems
