### ISSUE TITLE
css module not found

### ISSUE THREAD

**Issue by 00cyberghost** [simple-notify/simple-notify#47]
STEP TO REPRODUCE ISSUE(1.0.2)

npm install simple-notify

import simple notify in your project as advised from the docs

import Notify from 'simple-notify'
import 'simple-notify/dist/simple-notify.min.css'

ERROR
module not found 'simple-notify/dist/simple-notify.min.css'

STEP TO FIX THIS ISSUE
import Notify from 'simple-notify'
import 'simple-notify/dist/simple-notify.css'

today is 17th February 2024 and I noticed that a release was recently made. But the author forgot to add simple-notify.min.css and the documentation still recommends using this file.  So, i went over to the node modules folder and found out the minified CSS was missing.

**Comment by dgknca** [comment]
Hi. You're right. I forgot to update this part in readme. `simple-notify.css` file is already minified, therefore there is no `.min.css` file. Just updated the readme. Thanks for pointing out.
